name: Refresh JSON for GitHub Pages

on:
  schedule:
    - cron: "30 21 * * 1"   # Wednesday 12pm
  workflow_dispatch:

jobs:
  build-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to commit JSON back to the repo
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install Flask pandas requests numpy python-dateutil
          

      - name: Review Gaps and backfill
        env:
          OUT_DIR: docs/data
        run: |
          python scripts/check_gaps.py --log-file $OUT_DIR/gap_log.log
          python scripts/db_updater.py --db $OUT_DIR/timeseries.sqlite --backfill-days 60 --once

      - name: Generate station DB
        env:
          OUT_DIR: docs/data
          NDAYS: "7"
          # Add API keys as needed via repository "Actions secrets"
          NRW_KEY: ${{ secrets.NRW_KEY }}
        run: |
          python scripts/db_updater.py --db $OUT_DIR/timeseries.sqlite --once --fetch-days $NDAYS --log-file $OUT_DIR/test_update.log
          
      - name: Generate station JSON
        env:
          OUT_DIR: docs/data
          NRW_KEY: ${{ secrets.NRW_KEY }}
        run: |
          python scripts/db_to_json.py --db $OUT_DIR/timeseries.sqlite --output-dir $OUT_DIR

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/*.json docs/data/test_update.log
          git commit -m "Update JSON ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || echo "No changes"
          
          # safe fast‑forward pull
          git pull --ff-only
          
          git push
